version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    depends_on:
      - redis
    volumes:
      - ./:/code
    healthcheck:
      test: curl http://localhost:8000/healthcheck/ || exit 1
      interval: 30s
      timeout: 3s
    ports:
      - "8000:8000"

  redis:
    image: redis:6
